---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: mds.myfs.s1-1.kndfsl
  userKey: AQBTokJikRQfDxAAlhM74obOam2+yHjxV04E7g==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQC2ralhTfYNORAANsxt2D5vlKmon4jXWboyTw==
